export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

alias hv='/opt/mpmt-board-cli/highvoltage/hv.py --port /dev/ttyPS2'
alias hvmon=/opt/mpmt-board-cli/highvoltage/hvmon.py
alias rc=/opt/mpmt-board-cli/runcontrol/rc.py
alias sn=/opt/mpmt-board-cli/sensors/sn.py

export TERM=linux
