site_name: mPMT board documentation
repo_url: https://github.com/gtortone/mpmt-board
repo_name: gtortone/mpmt-board
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - toc.integrate
    - navigation.path
    - navigation.top
    - content.code.copy

markdown_extensions:
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences

